[versions]
algoutils = "0.4.0"

[libraries]
algoutils-student = { module = "org.tudalgo:algoutils-student", version.ref = "algoutils" }
algoutils-tutor = { module = "org.tudalgo:algoutils-tutor", version.ref = "algoutils" }
annotations = "org.jetbrains:annotations:23.0.0"
junit-core = { module = "org.junit.jupiter:junit-jupiter", version = "5.9.1" }
junit-pioneer = "org.junit-pioneer:junit-pioneer:1.7.1"
fopbot = "org.tudalgo:fopbot:0.4.1"

[plugins]
style = { id = "org.sourcegrade.style", version = "2.1.0" }
jagr-gradle = { id = "org.sourcegrade.jagr-gradle", version = "0.6.3" }
